package modelo.entidad;
// Generated 11/05/2015 09:44:32 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Evento generated by hbm2java
 */
public class Evento  implements java.io.Serializable {


     private String idEvento;
     private String nombreevento;
     private Date FInicioEvento;
     private Date FFinalEvento;
     private Date FIniciosuscrip;
     private Date FFinalsuscrip;
     private String horatotalEvento;
     private String porcenMinimoAsis;

    public Evento() {
    }

	
    public Evento(String idEvento) {
        this.idEvento = idEvento;
    }
    public Evento(String idEvento, String nombreevento, Date FInicioEvento, Date FFinalEvento, Date FIniciosuscrip, Date FFinalsuscrip, String horatotalEvento, String porcenMinimoAsis) {
       this.idEvento = idEvento;
       this.nombreevento = nombreevento;
       this.FInicioEvento = FInicioEvento;
       this.FFinalEvento = FFinalEvento;
       this.FIniciosuscrip = FIniciosuscrip;
       this.FFinalsuscrip = FFinalsuscrip;
       this.horatotalEvento = horatotalEvento;
       this.porcenMinimoAsis = porcenMinimoAsis;
    }
   
    public String getIdEvento() {
        return this.idEvento;
    }
    
    public void setIdEvento(String idEvento) {
        this.idEvento = idEvento;
    }
    public String getNombreevento() {
        return this.nombreevento;
    }
    
    public void setNombreevento(String nombreevento) {
        this.nombreevento = nombreevento;
    }
    public Date getFInicioEvento() {
        return this.FInicioEvento;
    }
    
    public void setFInicioEvento(Date FInicioEvento) {
        this.FInicioEvento = FInicioEvento;
    }
    public Date getFFinalEvento() {
        return this.FFinalEvento;
    }
    
    public void setFFinalEvento(Date FFinalEvento) {
        this.FFinalEvento = FFinalEvento;
    }
    public Date getFIniciosuscrip() {
        return this.FIniciosuscrip;
    }
    
    public void setFIniciosuscrip(Date FIniciosuscrip) {
        this.FIniciosuscrip = FIniciosuscrip;
    }
    public Date getFFinalsuscrip() {
        return this.FFinalsuscrip;
    }
    
    public void setFFinalsuscrip(Date FFinalsuscrip) {
        this.FFinalsuscrip = FFinalsuscrip;
    }
    public String getHoratotalEvento() {
        return this.horatotalEvento;
    }
    
    public void setHoratotalEvento(String horatotalEvento) {
        this.horatotalEvento = horatotalEvento;
    }
    public String getPorcenMinimoAsis() {
        return this.porcenMinimoAsis;
    }
    
    public void setPorcenMinimoAsis(String porcenMinimoAsis) {
        this.porcenMinimoAsis = porcenMinimoAsis;
    }




}


