package modelo.entidad;
// Generated 11/05/2015 09:44:32 PM by Hibernate Tools 4.3.1



/**
 * Medio generated by hbm2java
 */
public class Medio  implements java.io.Serializable {


     private String idMedio;
     private String nombre;

    public Medio() {
    }

	
    public Medio(String idMedio) {
        this.idMedio = idMedio;
    }
    public Medio(String idMedio, String nombre) {
       this.idMedio = idMedio;
       this.nombre = nombre;
    }
   
    public String getIdMedio() {
        return this.idMedio;
    }
    
    public void setIdMedio(String idMedio) {
        this.idMedio = idMedio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


