package modelo.entidad;
// Generated 11/05/2015 09:44:32 PM by Hibernate Tools 4.3.1



/**
 * TipoAsistente generated by hbm2java
 */
public class TipoAsistente  implements java.io.Serializable {


     private String idTipoasistente;
     private String nombretipoasis;

    public TipoAsistente() {
    }

	
    public TipoAsistente(String idTipoasistente) {
        this.idTipoasistente = idTipoasistente;
    }
    public TipoAsistente(String idTipoasistente, String nombretipoasis) {
       this.idTipoasistente = idTipoasistente;
       this.nombretipoasis = nombretipoasis;
    }
   
    public String getIdTipoasistente() {
        return this.idTipoasistente;
    }
    
    public void setIdTipoasistente(String idTipoasistente) {
        this.idTipoasistente = idTipoasistente;
    }
    public String getNombretipoasis() {
        return this.nombretipoasis;
    }
    
    public void setNombretipoasis(String nombretipoasis) {
        this.nombretipoasis = nombretipoasis;
    }




}


